name: case-navegacao-interior
channels:
- conda-forge
dependencies:
- python=3.11
- pip==23
- pip:
  - folium==0.14.0
  - geopandas==0.14.0
  - jupyter==1.0.0
  - matplotlib==3.7.2
  - numpy==1.25.2
  - pandas==2.1.0
  - plotly==5.16.1
  - black==23.7.0           #dev
  - flake8==6.1.0           #dev
  - isort==5.12.0           #dev
  - pylint==2.17.5          #dev